// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: rime/text_to_speech.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextToSpeech_Synthesize_FullMethodName            = "/rime.TextToSpeech/Synthesize"
	TextToSpeech_SynthesizeStreaming_FullMethodName   = "/rime.TextToSpeech/SynthesizeStreaming"
	TextToSpeech_NormalizeText_FullMethodName         = "/rime.TextToSpeech/NormalizeText"
	TextToSpeech_GetSupportedLanguages_FullMethodName = "/rime.TextToSpeech/GetSupportedLanguages"
	TextToSpeech_GetSupportedSpeakers_FullMethodName  = "/rime.TextToSpeech/GetSupportedSpeakers"
)

// TextToSpeechClient is the client API for TextToSpeech service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextToSpeechClient interface {
	Synthesize(ctx context.Context, in *SynthesisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesisResponseStream], error)
	// Streaming text input: the client feeds text incrementally into a single
	// continuous synthesis. The FIRST client message MUST set `header` (all
	// synthesis params; its `text` field may carry the first chunk or be empty);
	// subsequent messages set `text_chunk`. End-of-input is signalled by the
	// client half-closing the request stream. Audio frames stream back as they
	// are produced.
	SynthesizeStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingSynthesisRequest, SynthesisResponseStream], error)
	NormalizeText(ctx context.Context, in *NormalizeTextRequest, opts ...grpc.CallOption) (*NormalizeTextResponse, error)
	GetSupportedLanguages(ctx context.Context, in *GetSupportedLanguagesRequest, opts ...grpc.CallOption) (*GetSupportedLanguagesResponse, error)
	GetSupportedSpeakers(ctx context.Context, in *GetSupportedSpeakersRequest, opts ...grpc.CallOption) (*GetSupportedSpeakersResponse, error)
}

type textToSpeechClient struct {
	cc grpc.ClientConnInterface
}

func NewTextToSpeechClient(cc grpc.ClientConnInterface) TextToSpeechClient {
	return &textToSpeechClient{cc}
}

func (c *textToSpeechClient) Synthesize(ctx context.Context, in *SynthesisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesisResponseStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextToSpeech_ServiceDesc.Streams[0], TextToSpeech_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesisRequest, SynthesisResponseStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_SynthesizeClient = grpc.ServerStreamingClient[SynthesisResponseStream]

func (c *textToSpeechClient) SynthesizeStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingSynthesisRequest, SynthesisResponseStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextToSpeech_ServiceDesc.Streams[1], TextToSpeech_SynthesizeStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingSynthesisRequest, SynthesisResponseStream]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_SynthesizeStreamingClient = grpc.BidiStreamingClient[StreamingSynthesisRequest, SynthesisResponseStream]

func (c *textToSpeechClient) NormalizeText(ctx context.Context, in *NormalizeTextRequest, opts ...grpc.CallOption) (*NormalizeTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizeTextResponse)
	err := c.cc.Invoke(ctx, TextToSpeech_NormalizeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textToSpeechClient) GetSupportedLanguages(ctx context.Context, in *GetSupportedLanguagesRequest, opts ...grpc.CallOption) (*GetSupportedLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedLanguagesResponse)
	err := c.cc.Invoke(ctx, TextToSpeech_GetSupportedLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textToSpeechClient) GetSupportedSpeakers(ctx context.Context, in *GetSupportedSpeakersRequest, opts ...grpc.CallOption) (*GetSupportedSpeakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedSpeakersResponse)
	err := c.cc.Invoke(ctx, TextToSpeech_GetSupportedSpeakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextToSpeechServer is the server API for TextToSpeech service.
// All implementations must embed UnimplementedTextToSpeechServer
// for forward compatibility.
type TextToSpeechServer interface {
	Synthesize(*SynthesisRequest, grpc.ServerStreamingServer[SynthesisResponseStream]) error
	// Streaming text input: the client feeds text incrementally into a single
	// continuous synthesis. The FIRST client message MUST set `header` (all
	// synthesis params; its `text` field may carry the first chunk or be empty);
	// subsequent messages set `text_chunk`. End-of-input is signalled by the
	// client half-closing the request stream. Audio frames stream back as they
	// are produced.
	SynthesizeStreaming(grpc.BidiStreamingServer[StreamingSynthesisRequest, SynthesisResponseStream]) error
	NormalizeText(context.Context, *NormalizeTextRequest) (*NormalizeTextResponse, error)
	GetSupportedLanguages(context.Context, *GetSupportedLanguagesRequest) (*GetSupportedLanguagesResponse, error)
	GetSupportedSpeakers(context.Context, *GetSupportedSpeakersRequest) (*GetSupportedSpeakersResponse, error)
	mustEmbedUnimplementedTextToSpeechServer()
}

// UnimplementedTextToSpeechServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextToSpeechServer struct{}

func (UnimplementedTextToSpeechServer) Synthesize(*SynthesisRequest, grpc.ServerStreamingServer[SynthesisResponseStream]) error {
	return status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedTextToSpeechServer) SynthesizeStreaming(grpc.BidiStreamingServer[StreamingSynthesisRequest, SynthesisResponseStream]) error {
	return status.Error(codes.Unimplemented, "method SynthesizeStreaming not implemented")
}
func (UnimplementedTextToSpeechServer) NormalizeText(context.Context, *NormalizeTextRequest) (*NormalizeTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NormalizeText not implemented")
}
func (UnimplementedTextToSpeechServer) GetSupportedLanguages(context.Context, *GetSupportedLanguagesRequest) (*GetSupportedLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedLanguages not implemented")
}
func (UnimplementedTextToSpeechServer) GetSupportedSpeakers(context.Context, *GetSupportedSpeakersRequest) (*GetSupportedSpeakersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedSpeakers not implemented")
}
func (UnimplementedTextToSpeechServer) mustEmbedUnimplementedTextToSpeechServer() {}
func (UnimplementedTextToSpeechServer) testEmbeddedByValue()                      {}

// UnsafeTextToSpeechServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextToSpeechServer will
// result in compilation errors.
type UnsafeTextToSpeechServer interface {
	mustEmbedUnimplementedTextToSpeechServer()
}

func RegisterTextToSpeechServer(s grpc.ServiceRegistrar, srv TextToSpeechServer) {
	// If the following call panics, it indicates UnimplementedTextToSpeechServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextToSpeech_ServiceDesc, srv)
}

func _TextToSpeech_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesisRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextToSpeechServer).Synthesize(m, &grpc.GenericServerStream[SynthesisRequest, SynthesisResponseStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_SynthesizeServer = grpc.ServerStreamingServer[SynthesisResponseStream]

func _TextToSpeech_SynthesizeStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TextToSpeechServer).SynthesizeStreaming(&grpc.GenericServerStream[StreamingSynthesisRequest, SynthesisResponseStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_SynthesizeStreamingServer = grpc.BidiStreamingServer[StreamingSynthesisRequest, SynthesisResponseStream]

func _TextToSpeech_NormalizeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechServer).NormalizeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextToSpeech_NormalizeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechServer).NormalizeText(ctx, req.(*NormalizeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextToSpeech_GetSupportedLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechServer).GetSupportedLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextToSpeech_GetSupportedLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechServer).GetSupportedLanguages(ctx, req.(*GetSupportedLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextToSpeech_GetSupportedSpeakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedSpeakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechServer).GetSupportedSpeakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextToSpeech_GetSupportedSpeakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechServer).GetSupportedSpeakers(ctx, req.(*GetSupportedSpeakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextToSpeech_ServiceDesc is the grpc.ServiceDesc for TextToSpeech service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextToSpeech_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rime.TextToSpeech",
	HandlerType: (*TextToSpeechServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NormalizeText",
			Handler:    _TextToSpeech_NormalizeText_Handler,
		},
		{
			MethodName: "GetSupportedLanguages",
			Handler:    _TextToSpeech_GetSupportedLanguages_Handler,
		},
		{
			MethodName: "GetSupportedSpeakers",
			Handler:    _TextToSpeech_GetSupportedSpeakers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _TextToSpeech_Synthesize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeStreaming",
			Handler:       _TextToSpeech_SynthesizeStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rime/text_to_speech.proto",
}
