// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rime/text_to_speech.proto

package proto

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplitStrategy int32

const (
	SplitStrategy_SPLIT_STRATEGY_UNSPECIFIED SplitStrategy = 0
	SplitStrategy_SPLIT_STRATEGY_SENTENCE    SplitStrategy = 1
	SplitStrategy_SPLIT_STRATEGY_NONE        SplitStrategy = 2
	// Accumulates streamed sub-sentential text tokens into complete sentences
	// before synthesis. Only valid for streaming requests
	// (SynthesizeStreaming or the WebSocket API); a unary Synthesize request
	// that asks for it is rejected.
	SplitStrategy_SPLIT_STRATEGY_ACCUMULATE_SENTENCE SplitStrategy = 3
)

// Enum value maps for SplitStrategy.
var (
	SplitStrategy_name = map[int32]string{
		0: "SPLIT_STRATEGY_UNSPECIFIED",
		1: "SPLIT_STRATEGY_SENTENCE",
		2: "SPLIT_STRATEGY_NONE",
		3: "SPLIT_STRATEGY_ACCUMULATE_SENTENCE",
	}
	SplitStrategy_value = map[string]int32{
		"SPLIT_STRATEGY_UNSPECIFIED":         0,
		"SPLIT_STRATEGY_SENTENCE":            1,
		"SPLIT_STRATEGY_NONE":                2,
		"SPLIT_STRATEGY_ACCUMULATE_SENTENCE": 3,
	}
)

func (x SplitStrategy) Enum() *SplitStrategy {
	p := new(SplitStrategy)
	*p = x
	return p
}

func (x SplitStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_rime_text_to_speech_proto_enumTypes[0].Descriptor()
}

func (SplitStrategy) Type() protoreflect.EnumType {
	return &file_rime_text_to_speech_proto_enumTypes[0]
}

func (x SplitStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitStrategy.Descriptor instead.
func (SplitStrategy) EnumDescriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{0}
}

type StreamingSynthesisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamingSynthesisRequest_Header
	//	*StreamingSynthesisRequest_TextChunk
	Payload       isStreamingSynthesisRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingSynthesisRequest) Reset() {
	*x = StreamingSynthesisRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingSynthesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingSynthesisRequest) ProtoMessage() {}

func (x *StreamingSynthesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingSynthesisRequest.ProtoReflect.Descriptor instead.
func (*StreamingSynthesisRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingSynthesisRequest) GetPayload() isStreamingSynthesisRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamingSynthesisRequest) GetHeader() *SynthesisRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamingSynthesisRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *StreamingSynthesisRequest) GetTextChunk() string {
	if x != nil {
		if x, ok := x.Payload.(*StreamingSynthesisRequest_TextChunk); ok {
			return x.TextChunk
		}
	}
	return ""
}

type isStreamingSynthesisRequest_Payload interface {
	isStreamingSynthesisRequest_Payload()
}

type StreamingSynthesisRequest_Header struct {
	// FIRST message only: all synthesis parameters. Its `text` field may carry
	// the first complete sentence or be left empty.
	Header *SynthesisRequest `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type StreamingSynthesisRequest_TextChunk struct {
	// Subsequent messages: one complete sentence to append to the live
	// synthesis.
	TextChunk string `protobuf:"bytes,2,opt,name=text_chunk,json=textChunk,proto3,oneof"`
}

func (*StreamingSynthesisRequest_Header) isStreamingSynthesisRequest_Payload() {}

func (*StreamingSynthesisRequest_TextChunk) isStreamingSynthesisRequest_Payload() {}

type SynthesisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BCP-47 language tag, e.g. "en".
	// Used to route the frontend pipeline and set backend language.
	Language *string `protobuf:"bytes,2,opt,name=language,proto3,oneof" json:"language,omitempty"`
	// Speaker name, e.g. "luna".
	Speaker *string `protobuf:"bytes,3,opt,name=speaker,proto3,oneof" json:"speaker,omitempty"`
	// Text to synthesize.
	Text            string           `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	AudioParameters *AudioParameters `protobuf:"bytes,5,opt,name=audio_parameters,json=audioParameters,proto3,oneof" json:"audio_parameters,omitempty"`
	// Controls how input text is split before synthesis.
	// Defaults to SPLIT_STRATEGY_SENTENCE when unset.
	SplitStrategy  *SplitStrategy  `protobuf:"varint,6,opt,name=split_strategy,json=splitStrategy,proto3,enum=rime.SplitStrategy,oneof" json:"split_strategy,omitempty"`
	CodaParameters *CodaParameters `protobuf:"bytes,8,opt,name=coda_parameters,json=codaParameters,proto3,oneof" json:"coda_parameters,omitempty"`
	MistParameters *MistParameters `protobuf:"bytes,9,opt,name=mist_parameters,json=mistParameters,proto3,oneof" json:"mist_parameters,omitempty"`
	// Timestamps of the spoken spans of the synthesized audio, delivered in
	// the trailer once the audio has drained. Off unless requested.
	Timestamps    *TimestampOptions `protobuf:"bytes,10,opt,name=timestamps,proto3,oneof" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesisRequest) Reset() {
	*x = SynthesisRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisRequest) ProtoMessage() {}

func (x *SynthesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisRequest.ProtoReflect.Descriptor instead.
func (*SynthesisRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesisRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SynthesisRequest) GetSpeaker() string {
	if x != nil && x.Speaker != nil {
		return *x.Speaker
	}
	return ""
}

func (x *SynthesisRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesisRequest) GetAudioParameters() *AudioParameters {
	if x != nil {
		return x.AudioParameters
	}
	return nil
}

func (x *SynthesisRequest) GetSplitStrategy() SplitStrategy {
	if x != nil && x.SplitStrategy != nil {
		return *x.SplitStrategy
	}
	return SplitStrategy_SPLIT_STRATEGY_UNSPECIFIED
}

func (x *SynthesisRequest) GetCodaParameters() *CodaParameters {
	if x != nil {
		return x.CodaParameters
	}
	return nil
}

func (x *SynthesisRequest) GetMistParameters() *MistParameters {
	if x != nil {
		return x.MistParameters
	}
	return nil
}

func (x *SynthesisRequest) GetTimestamps() *TimestampOptions {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type SynthesisResponseStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SynthesisResponseStream_Audio
	//	*SynthesisResponseStream_Trailer
	Payload       isSynthesisResponseStream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesisResponseStream) Reset() {
	*x = SynthesisResponseStream{}
	mi := &file_rime_text_to_speech_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisResponseStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisResponseStream) ProtoMessage() {}

func (x *SynthesisResponseStream) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisResponseStream.ProtoReflect.Descriptor instead.
func (*SynthesisResponseStream) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{2}
}

func (x *SynthesisResponseStream) GetPayload() isSynthesisResponseStream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SynthesisResponseStream) GetAudio() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SynthesisResponseStream_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *SynthesisResponseStream) GetTrailer() *SynthesisResponseTrailer {
	if x != nil {
		if x, ok := x.Payload.(*SynthesisResponseStream_Trailer); ok {
			return x.Trailer
		}
	}
	return nil
}

type isSynthesisResponseStream_Payload interface {
	isSynthesisResponseStream_Payload()
}

type SynthesisResponseStream_Audio struct {
	// A chunk of encoded audio, in the format requested.
	Audio []byte `protobuf:"bytes,1,opt,name=audio,proto3,oneof"`
}

type SynthesisResponseStream_Trailer struct {
	// Sent once, after the last audio chunk, when the request asked for
	// anything it carries. A request that asked for nothing sees no trailer.
	Trailer *SynthesisResponseTrailer `protobuf:"bytes,2,opt,name=trailer,proto3,oneof"`
}

func (*SynthesisResponseStream_Audio) isSynthesisResponseStream_Payload() {}

func (*SynthesisResponseStream_Trailer) isSynthesisResponseStream_Payload() {}

// Results that settle only once the audio has drained.
type SynthesisResponseTrailer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present when `timestamps.enable` was set.
	Timestamps    *Timestamps `protobuf:"bytes,1,opt,name=timestamps,proto3,oneof" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesisResponseTrailer) Reset() {
	*x = SynthesisResponseTrailer{}
	mi := &file_rime_text_to_speech_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisResponseTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisResponseTrailer) ProtoMessage() {}

func (x *SynthesisResponseTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisResponseTrailer.ProtoReflect.Descriptor instead.
func (*SynthesisResponseTrailer) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesisResponseTrailer) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type AudioParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Equivalent to the HTTP `Accept` header.
	// Examples: "audio/wav", "audio/mpeg", "audio/ogg;codecs=opus", "audio/l16".
	AudioFormat     *string  `protobuf:"bytes,1,opt,name=audio_format,json=audioFormat,proto3,oneof" json:"audio_format,omitempty"`
	SamplingRate    *int32   `protobuf:"varint,2,opt,name=sampling_rate,json=samplingRate,proto3,oneof" json:"sampling_rate,omitempty"`
	TimeScaleFactor *float32 `protobuf:"fixed32,3,opt,name=time_scale_factor,json=timeScaleFactor,proto3,oneof" json:"time_scale_factor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioParameters) Reset() {
	*x = AudioParameters{}
	mi := &file_rime_text_to_speech_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioParameters) ProtoMessage() {}

func (x *AudioParameters) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioParameters.ProtoReflect.Descriptor instead.
func (*AudioParameters) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{4}
}

func (x *AudioParameters) GetAudioFormat() string {
	if x != nil && x.AudioFormat != nil {
		return *x.AudioFormat
	}
	return ""
}

func (x *AudioParameters) GetSamplingRate() int32 {
	if x != nil && x.SamplingRate != nil {
		return *x.SamplingRate
	}
	return 0
}

func (x *AudioParameters) GetTimeScaleFactor() float32 {
	if x != nil && x.TimeScaleFactor != nil {
		return *x.TimeScaleFactor
	}
	return 0
}

type CodaParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Streaming text input (`SynthesizeStreaming` / WebSocket `text`) only:
	// number of leading text tokens prefilled as a lookahead block so the first
	// audio frames have content context. Higher values improve content
	// robustness at the start of the utterance but delay the first audio until
	// that many text tokens have arrived. Clamped to the tokens available when
	// generation starts. Defaults to 0, which reproduces upstream Qwen3-TTS's
	// exact streaming layout. Ignored for one-shot synthesis (which always sees
	// the complete text up front).
	TextLookaheadTokens *int32 `protobuf:"varint,8,opt,name=text_lookahead_tokens,json=textLookaheadTokens,proto3,oneof" json:"text_lookahead_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CodaParameters) Reset() {
	*x = CodaParameters{}
	mi := &file_rime_text_to_speech_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodaParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodaParameters) ProtoMessage() {}

func (x *CodaParameters) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodaParameters.ProtoReflect.Descriptor instead.
func (*CodaParameters) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{5}
}

func (x *CodaParameters) GetTextLookaheadTokens() int32 {
	if x != nil && x.TextLookaheadTokens != nil {
		return *x.TextLookaheadTokens
	}
	return 0
}

type MistParameters struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PauseBetweenBrackets     *bool                  `protobuf:"varint,1,opt,name=pause_between_brackets,json=pauseBetweenBrackets,proto3,oneof" json:"pause_between_brackets,omitempty"`
	PhonemizeBetweenBrackets *bool                  `protobuf:"varint,2,opt,name=phonemize_between_brackets,json=phonemizeBetweenBrackets,proto3,oneof" json:"phonemize_between_brackets,omitempty"`
	InlineTimeScaleFactors   []float32              `protobuf:"fixed32,3,rep,packed,name=inline_time_scale_factors,json=inlineTimeScaleFactors,proto3" json:"inline_time_scale_factors,omitempty"`
	SaveOovs                 *bool                  `protobuf:"varint,4,opt,name=save_oovs,json=saveOovs,proto3,oneof" json:"save_oovs,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MistParameters) Reset() {
	*x = MistParameters{}
	mi := &file_rime_text_to_speech_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MistParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MistParameters) ProtoMessage() {}

func (x *MistParameters) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MistParameters.ProtoReflect.Descriptor instead.
func (*MistParameters) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{6}
}

func (x *MistParameters) GetPauseBetweenBrackets() bool {
	if x != nil && x.PauseBetweenBrackets != nil {
		return *x.PauseBetweenBrackets
	}
	return false
}

func (x *MistParameters) GetPhonemizeBetweenBrackets() bool {
	if x != nil && x.PhonemizeBetweenBrackets != nil {
		return *x.PhonemizeBetweenBrackets
	}
	return false
}

func (x *MistParameters) GetInlineTimeScaleFactors() []float32 {
	if x != nil {
		return x.InlineTimeScaleFactors
	}
	return nil
}

func (x *MistParameters) GetSaveOovs() bool {
	if x != nil && x.SaveOovs != nil {
		return *x.SaveOovs
	}
	return false
}

type TimestampOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Report a SpanTimestamp for every spoken span. Costs one aligner
	// inference per request; never delays or fails the audio.
	Enable        bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampOptions) Reset() {
	*x = TimestampOptions{}
	mi := &file_rime_text_to_speech_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampOptions) ProtoMessage() {}

func (x *TimestampOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampOptions.ProtoReflect.Descriptor instead.
func (*TimestampOptions) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{7}
}

func (x *TimestampOptions) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

// One span of the text the talker spoke, as the aligner segments it: a
// whitespace-separated word of the request text after normalization (so
// numbers and abbreviations appear spelled out), or a morpheme for a
// language written without spaces.
type SpanTimestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Offsets from the start of the synthesized audio, at the audio's native
	// rate and before `time_scale_factor`.
	Start         *durationpb.Duration `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *durationpb.Duration `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanTimestamp) Reset() {
	*x = SpanTimestamp{}
	mi := &file_rime_text_to_speech_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanTimestamp) ProtoMessage() {}

func (x *SpanTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanTimestamp.ProtoReflect.Descriptor instead.
func (*SpanTimestamp) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{8}
}

func (x *SpanTimestamp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SpanTimestamp) GetStart() *durationpb.Duration {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SpanTimestamp) GetEnd() *durationpb.Duration {
	if x != nil {
		return x.End
	}
	return nil
}

// The timestamps of one synthesis, delivered once after all audio: on gRPC
// as `trailer.timestamps`, on WebSocket as `done.timestamps`. Absent when
// the request did not ask for them. A non-OK status never fails the
// synthesis that produced the audio.
type Timestamps struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How the alignment settled, with `code` a google.rpc.Code. `OK` carries
	// spans; every other code carries none, with the reason in `message`:
	//   INVALID_ARGUMENT     the aligner does not support the request's
	//                        language, or rejected the utterance;
	//   RESOURCE_EXHAUSTED   the utterance exceeds what the aligner accepts,
	//                        or the branch lost input under load;
	//   DEADLINE_EXCEEDED    the aligner did not answer within its budget;
	//   UNAVAILABLE          the aligner worker is not serving;
	//   UNIMPLEMENTED        this package has no aligner;
	//   CANCELLED            synthesis ended before alignment settled.
	Status        *status.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Spans         []*SpanTimestamp `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamps) Reset() {
	*x = Timestamps{}
	mi := &file_rime_text_to_speech_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps) ProtoMessage() {}

func (x *Timestamps) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps.ProtoReflect.Descriptor instead.
func (*Timestamps) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{9}
}

func (x *Timestamps) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Timestamps) GetSpans() []*SpanTimestamp {
	if x != nil {
		return x.Spans
	}
	return nil
}

type NormalizeTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text to normalize.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// BCP-47 language tag, e.g. "en".
	Language      *string `protobuf:"bytes,2,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeTextRequest) Reset() {
	*x = NormalizeTextRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeTextRequest) ProtoMessage() {}

func (x *NormalizeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeTextRequest.ProtoReflect.Descriptor instead.
func (*NormalizeTextRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{10}
}

func (x *NormalizeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NormalizeTextRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type NormalizeTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: use normalized_sentences. Sentences are concatenated with no
	// whitespace separator, so multi-sentence inputs come back glued together.
	NormalizedText string `protobuf:"bytes,1,opt,name=normalized_text,json=normalizedText,proto3" json:"normalized_text,omitempty"`
	// The normalized text, one entry per sentence emitted by the frontend
	// pipeline. Each entry is already trimmed; join with a single space to
	// reconstruct display text.
	NormalizedSentences []string `protobuf:"bytes,2,rep,name=normalized_sentences,json=normalizedSentences,proto3" json:"normalized_sentences,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NormalizeTextResponse) Reset() {
	*x = NormalizeTextResponse{}
	mi := &file_rime_text_to_speech_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeTextResponse) ProtoMessage() {}

func (x *NormalizeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeTextResponse.ProtoReflect.Descriptor instead.
func (*NormalizeTextResponse) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{11}
}

func (x *NormalizeTextResponse) GetNormalizedText() string {
	if x != nil {
		return x.NormalizedText
	}
	return ""
}

func (x *NormalizeTextResponse) GetNormalizedSentences() []string {
	if x != nil {
		return x.NormalizedSentences
	}
	return nil
}

type GetSupportedLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedLanguagesRequest) Reset() {
	*x = GetSupportedLanguagesRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedLanguagesRequest) ProtoMessage() {}

func (x *GetSupportedLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedLanguagesRequest.ProtoReflect.Descriptor instead.
func (*GetSupportedLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{12}
}

type GetSupportedLanguagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of supported BCP-47 language tags.
	Languages     []string `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedLanguagesResponse) Reset() {
	*x = GetSupportedLanguagesResponse{}
	mi := &file_rime_text_to_speech_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedLanguagesResponse) ProtoMessage() {}

func (x *GetSupportedLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedLanguagesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{13}
}

func (x *GetSupportedLanguagesResponse) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type GetSupportedSpeakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *string                `protobuf:"bytes,1,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedSpeakersRequest) Reset() {
	*x = GetSupportedSpeakersRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedSpeakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedSpeakersRequest) ProtoMessage() {}

func (x *GetSupportedSpeakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedSpeakersRequest.ProtoReflect.Descriptor instead.
func (*GetSupportedSpeakersRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{14}
}

func (x *GetSupportedSpeakersRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type GetSupportedSpeakersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of supported speaker names for the given language.
	Speakers      []string `protobuf:"bytes,1,rep,name=speakers,proto3" json:"speakers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedSpeakersResponse) Reset() {
	*x = GetSupportedSpeakersResponse{}
	mi := &file_rime_text_to_speech_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedSpeakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedSpeakersResponse) ProtoMessage() {}

func (x *GetSupportedSpeakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedSpeakersResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedSpeakersResponse) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{15}
}

func (x *GetSupportedSpeakersResponse) GetSpeakers() []string {
	if x != nil {
		return x.Speakers
	}
	return nil
}

// Client -> server. Exactly one message per WebSocket frame.
type WebSocketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-chosen context identifier, at most 128 bytes. Empty selects the
	// context named "default". An identifier may be reused after its context
	// reaches a terminal event.
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketRequest_Config
	//	*WebSocketRequest_Start
	//	*WebSocketRequest_Text
	//	*WebSocketRequest_End
	//	*WebSocketRequest_Cancel
	Payload       isWebSocketRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketRequest) Reset() {
	*x = WebSocketRequest{}
	mi := &file_rime_text_to_speech_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketRequest) ProtoMessage() {}

func (x *WebSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketRequest.ProtoReflect.Descriptor instead.
func (*WebSocketRequest) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{16}
}

func (x *WebSocketRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *WebSocketRequest) GetPayload() isWebSocketRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketRequest) GetConfig() *WebSocketConfig {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *WebSocketRequest) GetStart() *SynthesisRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *WebSocketRequest) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *WebSocketRequest) GetEnd() *WebSocketEnd {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketRequest_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *WebSocketRequest) GetCancel() *WebSocketCancel {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isWebSocketRequest_Payload interface {
	isWebSocketRequest_Payload()
}

type WebSocketRequest_Config struct {
	// Connection-level configuration. At most one, and only before the first
	// `start`. Not required in debug mode or when the upgrade request
	// carried an `Authorization` header.
	Config *WebSocketConfig `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type WebSocketRequest_Start struct {
	// Opens the context with the full synthesis parameters. A non-empty
	// `text` is the complete input for one-shot synthesis: audio streams
	// and ends with `done`, no `end` required. An empty `text` opens a
	// streaming context that stays open for `text` messages and finalizes
	// on `end`.
	Start *SynthesisRequest `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type WebSocketRequest_Text struct {
	// Appends a chunk of input text to an open streaming context (one opened
	// with an empty `start.text`). The engine meters, segments, and
	// synthesizes it into the same continuous audio as it arrives. Rejected
	// with kind "invalid_input" if the context is not open for input (no
	// `start`, or already `end`ed / one-shot).
	Text string `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type WebSocketRequest_End struct {
	// Declares end of input for a streaming context. Remaining audio is
	// delivered, followed by `done`. A no-op for a one-shot context. The
	// connection stays open for further contexts.
	End *WebSocketEnd `protobuf:"bytes,5,opt,name=end,proto3,oneof"`
}

type WebSocketRequest_Cancel struct {
	// Aborts the context immediately, discarding in-flight synthesis.
	// Acknowledged with `cancelled`; idempotent (cancelling an unknown or
	// finished context is not an error).
	Cancel *WebSocketCancel `protobuf:"bytes,6,opt,name=cancel,proto3,oneof"`
}

func (*WebSocketRequest_Config) isWebSocketRequest_Payload() {}

func (*WebSocketRequest_Start) isWebSocketRequest_Payload() {}

func (*WebSocketRequest_Text) isWebSocketRequest_Payload() {}

func (*WebSocketRequest_End) isWebSocketRequest_Payload() {}

func (*WebSocketRequest_Cancel) isWebSocketRequest_Payload() {}

type WebSocketConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mirrors the HTTP `Authorization` header, e.g. "Api-Key <key>".
	// Rejected if the upgrade request already carried an Authorization header.
	Authorization *string `protobuf:"bytes,1,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	// License JSON for on-prem deployments; mirrors the `x-rime-license`
	// gRPC metadata / the `license` field of the HTTP API.
	License *string `protobuf:"bytes,2,opt,name=license,proto3,oneof" json:"license,omitempty"`
	// Defaults merged (field-wise, shallow) under every subsequent `start`.
	// Its `text` field is ignored.
	Defaults      *SynthesisRequest `protobuf:"bytes,3,opt,name=defaults,proto3,oneof" json:"defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketConfig) Reset() {
	*x = WebSocketConfig{}
	mi := &file_rime_text_to_speech_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketConfig) ProtoMessage() {}

func (x *WebSocketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketConfig.ProtoReflect.Descriptor instead.
func (*WebSocketConfig) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{17}
}

func (x *WebSocketConfig) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *WebSocketConfig) GetLicense() string {
	if x != nil && x.License != nil {
		return *x.License
	}
	return ""
}

func (x *WebSocketConfig) GetDefaults() *SynthesisRequest {
	if x != nil {
		return x.Defaults
	}
	return nil
}

type WebSocketEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketEnd) Reset() {
	*x = WebSocketEnd{}
	mi := &file_rime_text_to_speech_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketEnd) ProtoMessage() {}

func (x *WebSocketEnd) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketEnd.ProtoReflect.Descriptor instead.
func (*WebSocketEnd) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{18}
}

type WebSocketCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketCancel) Reset() {
	*x = WebSocketCancel{}
	mi := &file_rime_text_to_speech_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketCancel) ProtoMessage() {}

func (x *WebSocketCancel) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketCancel.ProtoReflect.Descriptor instead.
func (*WebSocketCancel) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{19}
}

// Server -> client. Exactly one message per WebSocket frame.
type WebSocketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Context the payload applies to. Empty for connection-scoped payloads
	// (`ready` and connection-level `error`s).
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketResponse_Ready
	//	*WebSocketResponse_Started
	//	*WebSocketResponse_Audio
	//	*WebSocketResponse_Done
	//	*WebSocketResponse_Cancelled
	//	*WebSocketResponse_Error
	Payload       isWebSocketResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketResponse) Reset() {
	*x = WebSocketResponse{}
	mi := &file_rime_text_to_speech_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketResponse) ProtoMessage() {}

func (x *WebSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketResponse.ProtoReflect.Descriptor instead.
func (*WebSocketResponse) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{20}
}

func (x *WebSocketResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *WebSocketResponse) GetPayload() isWebSocketResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketResponse) GetReady() *WebSocketReady {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *WebSocketResponse) GetStarted() *WebSocketStarted {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *WebSocketResponse) GetAudio() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *WebSocketResponse) GetDone() *WebSocketDone {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *WebSocketResponse) GetCancelled() *WebSocketCancelled {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *WebSocketResponse) GetError() *WebSocketError {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWebSocketResponse_Payload interface {
	isWebSocketResponse_Payload()
}

type WebSocketResponse_Ready struct {
	// Sent once per connection when the engine is ready to synthesize
	// (pipelines loaded and serving). Gate `start` on this event.
	Ready *WebSocketReady `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type WebSocketResponse_Started struct {
	// The context was accepted; precedes any of its audio.
	Started *WebSocketStarted `protobuf:"bytes,3,opt,name=started,proto3,oneof"`
}

type WebSocketResponse_Audio struct {
	// A chunk of encoded audio, in the format requested at `start`.
	Audio []byte `protobuf:"bytes,4,opt,name=audio,proto3,oneof"`
}

type WebSocketResponse_Done struct {
	// Terminal: all audio for the context has been delivered.
	Done *WebSocketDone `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

type WebSocketResponse_Cancelled struct {
	// Terminal: the context was aborted by `cancel`.
	Cancelled *WebSocketCancelled `protobuf:"bytes,6,opt,name=cancelled,proto3,oneof"`
}

type WebSocketResponse_Error struct {
	// Terminal for the context it names. Errors with an empty `context_id`
	// are connection-scoped and leave open contexts running; the server
	// closes the connection only when the failure is unrecoverable
	// (undecodable frames, failed authentication).
	Error *WebSocketError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*WebSocketResponse_Ready) isWebSocketResponse_Payload() {}

func (*WebSocketResponse_Started) isWebSocketResponse_Payload() {}

func (*WebSocketResponse_Audio) isWebSocketResponse_Payload() {}

func (*WebSocketResponse_Done) isWebSocketResponse_Payload() {}

func (*WebSocketResponse_Cancelled) isWebSocketResponse_Payload() {}

func (*WebSocketResponse_Error) isWebSocketResponse_Payload() {}

type WebSocketReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version. Currently 1.
	Protocol uint32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Supported BCP-47 language tags (mirrors GetSupportedLanguages).
	Languages       []string `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	DefaultLanguage *string  `protobuf:"bytes,3,opt,name=default_language,json=defaultLanguage,proto3,oneof" json:"default_language,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebSocketReady) Reset() {
	*x = WebSocketReady{}
	mi := &file_rime_text_to_speech_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketReady) ProtoMessage() {}

func (x *WebSocketReady) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketReady.ProtoReflect.Descriptor instead.
func (*WebSocketReady) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{21}
}

func (x *WebSocketReady) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *WebSocketReady) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *WebSocketReady) GetDefaultLanguage() string {
	if x != nil && x.DefaultLanguage != nil {
		return *x.DefaultLanguage
	}
	return ""
}

type WebSocketStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Engine request id for this context; correlates with engine logs and
	// matches the `x-request-id` gRPC/HTTP metadata.
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketStarted) Reset() {
	*x = WebSocketStarted{}
	mi := &file_rime_text_to_speech_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketStarted) ProtoMessage() {}

func (x *WebSocketStarted) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketStarted.ProtoReflect.Descriptor instead.
func (*WebSocketStarted) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{22}
}

func (x *WebSocketStarted) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type WebSocketDone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present when `start.timestamps.enable` was set.
	Timestamps    *Timestamps `protobuf:"bytes,1,opt,name=timestamps,proto3,oneof" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketDone) Reset() {
	*x = WebSocketDone{}
	mi := &file_rime_text_to_speech_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketDone) ProtoMessage() {}

func (x *WebSocketDone) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketDone.ProtoReflect.Descriptor instead.
func (*WebSocketDone) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{23}
}

func (x *WebSocketDone) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type WebSocketCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketCancelled) Reset() {
	*x = WebSocketCancelled{}
	mi := &file_rime_text_to_speech_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketCancelled) ProtoMessage() {}

func (x *WebSocketCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketCancelled.ProtoReflect.Descriptor instead.
func (*WebSocketCancelled) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{24}
}

type WebSocketError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable machine-readable kind; same values as the HTTP error body
	// (e.g. "invalid_input", "unauthenticated", "unavailable", "internal",
	// "unimplemented").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Human-readable description.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Engine request id, when the error occurred inside a synthesis request.
	RequestId     *string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketError) Reset() {
	*x = WebSocketError{}
	mi := &file_rime_text_to_speech_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketError) ProtoMessage() {}

func (x *WebSocketError) ProtoReflect() protoreflect.Message {
	mi := &file_rime_text_to_speech_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketError.ProtoReflect.Descriptor instead.
func (*WebSocketError) Descriptor() ([]byte, []int) {
	return file_rime_text_to_speech_proto_rawDescGZIP(), []int{25}
}

func (x *WebSocketError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WebSocketError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WebSocketError) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

var File_rime_text_to_speech_proto protoreflect.FileDescriptor

const file_rime_text_to_speech_proto_rawDesc = "" +
	"\n" +
	"\x19rime/text_to_speech.proto\x12\x04rime\x1a\x1egoogle/protobuf/duration.proto\x1a\x17google/rpc/status.proto\"\x86\x01\n" +
	"\x19StreamingSynthesisRequest\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x16.rime.SynthesisRequestH\x00R\x06header\x12\x1f\n" +
	"\n" +
	"text_chunk\x18\x02 \x01(\tH\x00R\ttextChunkB\t\n" +
	"\apayloadJ\x04\b\x03\x10\x04R\x05flush\"\xca\x04\n" +
	"\x10SynthesisRequest\x12\x1f\n" +
	"\blanguage\x18\x02 \x01(\tH\x00R\blanguage\x88\x01\x01\x12\x1d\n" +
	"\aspeaker\x18\x03 \x01(\tH\x01R\aspeaker\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12E\n" +
	"\x10audio_parameters\x18\x05 \x01(\v2\x15.rime.AudioParametersH\x02R\x0faudioParameters\x88\x01\x01\x12?\n" +
	"\x0esplit_strategy\x18\x06 \x01(\x0e2\x13.rime.SplitStrategyH\x03R\rsplitStrategy\x88\x01\x01\x12B\n" +
	"\x0fcoda_parameters\x18\b \x01(\v2\x14.rime.CodaParametersH\x04R\x0ecodaParameters\x88\x01\x01\x12B\n" +
	"\x0fmist_parameters\x18\t \x01(\v2\x14.rime.MistParametersH\x05R\x0emistParameters\x88\x01\x01\x12;\n" +
	"\n" +
	"timestamps\x18\n" +
	" \x01(\v2\x16.rime.TimestampOptionsH\x06R\n" +
	"timestamps\x88\x01\x01B\v\n" +
	"\t_languageB\n" +
	"\n" +
	"\b_speakerB\x13\n" +
	"\x11_audio_parametersB\x11\n" +
	"\x0f_split_strategyB\x12\n" +
	"\x10_coda_parametersB\x12\n" +
	"\x10_mist_parametersB\r\n" +
	"\v_timestampsJ\x04\b\x01\x10\x02J\x04\b\a\x10\bR\x11arcana_parameters\"x\n" +
	"\x17SynthesisResponseStream\x12\x16\n" +
	"\x05audio\x18\x01 \x01(\fH\x00R\x05audio\x12:\n" +
	"\atrailer\x18\x02 \x01(\v2\x1e.rime.SynthesisResponseTrailerH\x00R\atrailerB\t\n" +
	"\apayload\"`\n" +
	"\x18SynthesisResponseTrailer\x125\n" +
	"\n" +
	"timestamps\x18\x01 \x01(\v2\x10.rime.TimestampsH\x00R\n" +
	"timestamps\x88\x01\x01B\r\n" +
	"\v_timestamps\"\xcd\x01\n" +
	"\x0fAudioParameters\x12&\n" +
	"\faudio_format\x18\x01 \x01(\tH\x00R\vaudioFormat\x88\x01\x01\x12(\n" +
	"\rsampling_rate\x18\x02 \x01(\x05H\x01R\fsamplingRate\x88\x01\x01\x12/\n" +
	"\x11time_scale_factor\x18\x03 \x01(\x02H\x02R\x0ftimeScaleFactor\x88\x01\x01B\x0f\n" +
	"\r_audio_formatB\x10\n" +
	"\x0e_sampling_rateB\x14\n" +
	"\x12_time_scale_factor\"\xda\x01\n" +
	"\x0eCodaParameters\x127\n" +
	"\x15text_lookahead_tokens\x18\b \x01(\x05H\x00R\x13textLookaheadTokens\x88\x01\x01B\x18\n" +
	"\x16_text_lookahead_tokensJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bR\vtemperatureR\x05top_kR\x05top_pR\x12repetition_penaltyR\n" +
	"max_tokensR\n" +
	"min_tokensR\x04seed\"\xb3\x02\n" +
	"\x0eMistParameters\x129\n" +
	"\x16pause_between_brackets\x18\x01 \x01(\bH\x00R\x14pauseBetweenBrackets\x88\x01\x01\x12A\n" +
	"\x1aphonemize_between_brackets\x18\x02 \x01(\bH\x01R\x18phonemizeBetweenBrackets\x88\x01\x01\x129\n" +
	"\x19inline_time_scale_factors\x18\x03 \x03(\x02R\x16inlineTimeScaleFactors\x12 \n" +
	"\tsave_oovs\x18\x04 \x01(\bH\x02R\bsaveOovs\x88\x01\x01B\x19\n" +
	"\x17_pause_between_bracketsB\x1d\n" +
	"\x1b_phonemize_between_bracketsB\f\n" +
	"\n" +
	"_save_oovs\"*\n" +
	"\x10TimestampOptions\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"\x81\x01\n" +
	"\rSpanTimestamp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12/\n" +
	"\x05start\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05start\x12+\n" +
	"\x03end\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03end\"c\n" +
	"\n" +
	"Timestamps\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12)\n" +
	"\x05spans\x18\x02 \x03(\v2\x13.rime.SpanTimestampR\x05spans\"X\n" +
	"\x14NormalizeTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\blanguage\x18\x02 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\"s\n" +
	"\x15NormalizeTextResponse\x12'\n" +
	"\x0fnormalized_text\x18\x01 \x01(\tR\x0enormalizedText\x121\n" +
	"\x14normalized_sentences\x18\x02 \x03(\tR\x13normalizedSentences\"\x1e\n" +
	"\x1cGetSupportedLanguagesRequest\"=\n" +
	"\x1dGetSupportedLanguagesResponse\x12\x1c\n" +
	"\tlanguages\x18\x01 \x03(\tR\tlanguages\"K\n" +
	"\x1bGetSupportedSpeakersRequest\x12\x1f\n" +
	"\blanguage\x18\x01 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\":\n" +
	"\x1cGetSupportedSpeakersResponse\x12\x1a\n" +
	"\bspeakers\x18\x01 \x03(\tR\bspeakers\"\x99\x02\n" +
	"\x10WebSocketRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x15.rime.WebSocketConfigH\x00R\x06config\x12.\n" +
	"\x05start\x18\x03 \x01(\v2\x16.rime.SynthesisRequestH\x00R\x05start\x12\x14\n" +
	"\x04text\x18\x04 \x01(\tH\x00R\x04text\x12&\n" +
	"\x03end\x18\x05 \x01(\v2\x12.rime.WebSocketEndH\x00R\x03end\x12/\n" +
	"\x06cancel\x18\x06 \x01(\v2\x15.rime.WebSocketCancelH\x00R\x06cancelB\t\n" +
	"\apayloadJ\x04\b\a\x10\bR\x05flush\"\xbf\x01\n" +
	"\x0fWebSocketConfig\x12)\n" +
	"\rauthorization\x18\x01 \x01(\tH\x00R\rauthorization\x88\x01\x01\x12\x1d\n" +
	"\alicense\x18\x02 \x01(\tH\x01R\alicense\x88\x01\x01\x127\n" +
	"\bdefaults\x18\x03 \x01(\v2\x16.rime.SynthesisRequestH\x02R\bdefaults\x88\x01\x01B\x10\n" +
	"\x0e_authorizationB\n" +
	"\n" +
	"\b_licenseB\v\n" +
	"\t_defaults\"\x0e\n" +
	"\fWebSocketEnd\"\x11\n" +
	"\x0fWebSocketCancel\"\xca\x02\n" +
	"\x11WebSocketResponse\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12,\n" +
	"\x05ready\x18\x02 \x01(\v2\x14.rime.WebSocketReadyH\x00R\x05ready\x122\n" +
	"\astarted\x18\x03 \x01(\v2\x16.rime.WebSocketStartedH\x00R\astarted\x12\x16\n" +
	"\x05audio\x18\x04 \x01(\fH\x00R\x05audio\x12)\n" +
	"\x04done\x18\x05 \x01(\v2\x13.rime.WebSocketDoneH\x00R\x04done\x128\n" +
	"\tcancelled\x18\x06 \x01(\v2\x18.rime.WebSocketCancelledH\x00R\tcancelled\x12,\n" +
	"\x05error\x18\a \x01(\v2\x14.rime.WebSocketErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\x0eWebSocketReady\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12.\n" +
	"\x10default_language\x18\x03 \x01(\tH\x00R\x0fdefaultLanguage\x88\x01\x01B\x13\n" +
	"\x11_default_language\"1\n" +
	"\x10WebSocketStarted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"U\n" +
	"\rWebSocketDone\x125\n" +
	"\n" +
	"timestamps\x18\x01 \x01(\v2\x10.rime.TimestampsH\x00R\n" +
	"timestamps\x88\x01\x01B\r\n" +
	"\v_timestamps\"\x14\n" +
	"\x12WebSocketCancelled\"q\n" +
	"\x0eWebSocketError\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tH\x00R\trequestId\x88\x01\x01B\r\n" +
	"\v_request_id*\x8d\x01\n" +
	"\rSplitStrategy\x12\x1e\n" +
	"\x1aSPLIT_STRATEGY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SPLIT_STRATEGY_SENTENCE\x10\x01\x12\x17\n" +
	"\x13SPLIT_STRATEGY_NONE\x10\x02\x12&\n" +
	"\"SPLIT_STRATEGY_ACCUMULATE_SENTENCE\x10\x032\xc5\x03\n" +
	"\fTextToSpeech\x12G\n" +
	"\n" +
	"Synthesize\x12\x16.rime.SynthesisRequest\x1a\x1d.rime.SynthesisResponseStream\"\x000\x01\x12[\n" +
	"\x13SynthesizeStreaming\x12\x1f.rime.StreamingSynthesisRequest\x1a\x1d.rime.SynthesisResponseStream\"\x00(\x010\x01\x12J\n" +
	"\rNormalizeText\x12\x1a.rime.NormalizeTextRequest\x1a\x1b.rime.NormalizeTextResponse\"\x00\x12b\n" +
	"\x15GetSupportedLanguages\x12\".rime.GetSupportedLanguagesRequest\x1a#.rime.GetSupportedLanguagesResponse\"\x00\x12_\n" +
	"\x14GetSupportedSpeakers\x12!.rime.GetSupportedSpeakersRequest\x1a\".rime.GetSupportedSpeakersResponse\"\x00b\x06proto3"

var (
	file_rime_text_to_speech_proto_rawDescOnce sync.Once
	file_rime_text_to_speech_proto_rawDescData []byte
)

func file_rime_text_to_speech_proto_rawDescGZIP() []byte {
	file_rime_text_to_speech_proto_rawDescOnce.Do(func() {
		file_rime_text_to_speech_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rime_text_to_speech_proto_rawDesc), len(file_rime_text_to_speech_proto_rawDesc)))
	})
	return file_rime_text_to_speech_proto_rawDescData
}

var file_rime_text_to_speech_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rime_text_to_speech_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_rime_text_to_speech_proto_goTypes = []any{
	(SplitStrategy)(0),                    // 0: rime.SplitStrategy
	(*StreamingSynthesisRequest)(nil),     // 1: rime.StreamingSynthesisRequest
	(*SynthesisRequest)(nil),              // 2: rime.SynthesisRequest
	(*SynthesisResponseStream)(nil),       // 3: rime.SynthesisResponseStream
	(*SynthesisResponseTrailer)(nil),      // 4: rime.SynthesisResponseTrailer
	(*AudioParameters)(nil),               // 5: rime.AudioParameters
	(*CodaParameters)(nil),                // 6: rime.CodaParameters
	(*MistParameters)(nil),                // 7: rime.MistParameters
	(*TimestampOptions)(nil),              // 8: rime.TimestampOptions
	(*SpanTimestamp)(nil),                 // 9: rime.SpanTimestamp
	(*Timestamps)(nil),                    // 10: rime.Timestamps
	(*NormalizeTextRequest)(nil),          // 11: rime.NormalizeTextRequest
	(*NormalizeTextResponse)(nil),         // 12: rime.NormalizeTextResponse
	(*GetSupportedLanguagesRequest)(nil),  // 13: rime.GetSupportedLanguagesRequest
	(*GetSupportedLanguagesResponse)(nil), // 14: rime.GetSupportedLanguagesResponse
	(*GetSupportedSpeakersRequest)(nil),   // 15: rime.GetSupportedSpeakersRequest
	(*GetSupportedSpeakersResponse)(nil),  // 16: rime.GetSupportedSpeakersResponse
	(*WebSocketRequest)(nil),              // 17: rime.WebSocketRequest
	(*WebSocketConfig)(nil),               // 18: rime.WebSocketConfig
	(*WebSocketEnd)(nil),                  // 19: rime.WebSocketEnd
	(*WebSocketCancel)(nil),               // 20: rime.WebSocketCancel
	(*WebSocketResponse)(nil),             // 21: rime.WebSocketResponse
	(*WebSocketReady)(nil),                // 22: rime.WebSocketReady
	(*WebSocketStarted)(nil),              // 23: rime.WebSocketStarted
	(*WebSocketDone)(nil),                 // 24: rime.WebSocketDone
	(*WebSocketCancelled)(nil),            // 25: rime.WebSocketCancelled
	(*WebSocketError)(nil),                // 26: rime.WebSocketError
	(*durationpb.Duration)(nil),           // 27: google.protobuf.Duration
	(*status.Status)(nil),                 // 28: google.rpc.Status
}
var file_rime_text_to_speech_proto_depIdxs = []int32{
	2,  // 0: rime.StreamingSynthesisRequest.header:type_name -> rime.SynthesisRequest
	5,  // 1: rime.SynthesisRequest.audio_parameters:type_name -> rime.AudioParameters
	0,  // 2: rime.SynthesisRequest.split_strategy:type_name -> rime.SplitStrategy
	6,  // 3: rime.SynthesisRequest.coda_parameters:type_name -> rime.CodaParameters
	7,  // 4: rime.SynthesisRequest.mist_parameters:type_name -> rime.MistParameters
	8,  // 5: rime.SynthesisRequest.timestamps:type_name -> rime.TimestampOptions
	4,  // 6: rime.SynthesisResponseStream.trailer:type_name -> rime.SynthesisResponseTrailer
	10, // 7: rime.SynthesisResponseTrailer.timestamps:type_name -> rime.Timestamps
	27, // 8: rime.SpanTimestamp.start:type_name -> google.protobuf.Duration
	27, // 9: rime.SpanTimestamp.end:type_name -> google.protobuf.Duration
	28, // 10: rime.Timestamps.status:type_name -> google.rpc.Status
	9,  // 11: rime.Timestamps.spans:type_name -> rime.SpanTimestamp
	18, // 12: rime.WebSocketRequest.config:type_name -> rime.WebSocketConfig
	2,  // 13: rime.WebSocketRequest.start:type_name -> rime.SynthesisRequest
	19, // 14: rime.WebSocketRequest.end:type_name -> rime.WebSocketEnd
	20, // 15: rime.WebSocketRequest.cancel:type_name -> rime.WebSocketCancel
	2,  // 16: rime.WebSocketConfig.defaults:type_name -> rime.SynthesisRequest
	22, // 17: rime.WebSocketResponse.ready:type_name -> rime.WebSocketReady
	23, // 18: rime.WebSocketResponse.started:type_name -> rime.WebSocketStarted
	24, // 19: rime.WebSocketResponse.done:type_name -> rime.WebSocketDone
	25, // 20: rime.WebSocketResponse.cancelled:type_name -> rime.WebSocketCancelled
	26, // 21: rime.WebSocketResponse.error:type_name -> rime.WebSocketError
	10, // 22: rime.WebSocketDone.timestamps:type_name -> rime.Timestamps
	2,  // 23: rime.TextToSpeech.Synthesize:input_type -> rime.SynthesisRequest
	1,  // 24: rime.TextToSpeech.SynthesizeStreaming:input_type -> rime.StreamingSynthesisRequest
	11, // 25: rime.TextToSpeech.NormalizeText:input_type -> rime.NormalizeTextRequest
	13, // 26: rime.TextToSpeech.GetSupportedLanguages:input_type -> rime.GetSupportedLanguagesRequest
	15, // 27: rime.TextToSpeech.GetSupportedSpeakers:input_type -> rime.GetSupportedSpeakersRequest
	3,  // 28: rime.TextToSpeech.Synthesize:output_type -> rime.SynthesisResponseStream
	3,  // 29: rime.TextToSpeech.SynthesizeStreaming:output_type -> rime.SynthesisResponseStream
	12, // 30: rime.TextToSpeech.NormalizeText:output_type -> rime.NormalizeTextResponse
	14, // 31: rime.TextToSpeech.GetSupportedLanguages:output_type -> rime.GetSupportedLanguagesResponse
	16, // 32: rime.TextToSpeech.GetSupportedSpeakers:output_type -> rime.GetSupportedSpeakersResponse
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_rime_text_to_speech_proto_init() }
func file_rime_text_to_speech_proto_init() {
	if File_rime_text_to_speech_proto != nil {
		return
	}
	file_rime_text_to_speech_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamingSynthesisRequest_Header)(nil),
		(*StreamingSynthesisRequest_TextChunk)(nil),
	}
	file_rime_text_to_speech_proto_msgTypes[1].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[2].OneofWrappers = []any{
		(*SynthesisResponseStream_Audio)(nil),
		(*SynthesisResponseStream_Trailer)(nil),
	}
	file_rime_text_to_speech_proto_msgTypes[3].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[4].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[5].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[6].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[10].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[14].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[16].OneofWrappers = []any{
		(*WebSocketRequest_Config)(nil),
		(*WebSocketRequest_Start)(nil),
		(*WebSocketRequest_Text)(nil),
		(*WebSocketRequest_End)(nil),
		(*WebSocketRequest_Cancel)(nil),
	}
	file_rime_text_to_speech_proto_msgTypes[17].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[20].OneofWrappers = []any{
		(*WebSocketResponse_Ready)(nil),
		(*WebSocketResponse_Started)(nil),
		(*WebSocketResponse_Audio)(nil),
		(*WebSocketResponse_Done)(nil),
		(*WebSocketResponse_Cancelled)(nil),
		(*WebSocketResponse_Error)(nil),
	}
	file_rime_text_to_speech_proto_msgTypes[21].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[23].OneofWrappers = []any{}
	file_rime_text_to_speech_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rime_text_to_speech_proto_rawDesc), len(file_rime_text_to_speech_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rime_text_to_speech_proto_goTypes,
		DependencyIndexes: file_rime_text_to_speech_proto_depIdxs,
		EnumInfos:         file_rime_text_to_speech_proto_enumTypes,
		MessageInfos:      file_rime_text_to_speech_proto_msgTypes,
	}.Build()
	File_rime_text_to_speech_proto = out.File
	file_rime_text_to_speech_proto_goTypes = nil
	file_rime_text_to_speech_proto_depIdxs = nil
}
