from collections.abc import Awaitable

class NativeClient:
    def __init__(self, config: str) -> None: ...
    @staticmethod
    def testing(config: str, target: str, policy: str) -> NativeClient: ...
    def stream(self, options: str) -> NativeStream: ...
    def discover(
        self, voices: bool, language: str | None, timeout: float | None, inherit: bool
    ) -> Awaitable[list[str]]: ...
    def close(self) -> Awaitable[None]: ...
    def cancel(self) -> None: ...

class NativeStream:
    @property
    def request_id(self) -> str | None: ...
    @property
    def input_done(self) -> bool: ...
    @property
    def source_chars(self) -> int: ...
    @property
    def cleanup_timeout(self) -> float: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def fail_source(self) -> None: ...
    def wait_stopped(self) -> Awaitable[None]: ...
    def wait_produced(self) -> Awaitable[None]: ...
    def accept_read(self, ticket: int) -> None: ...
    def input_reply(self, value: str) -> None: ...
    def input_request(self) -> Awaitable[int | None]: ...
    def read(self) -> Awaitable[tuple[bytes | None, int]]: ...

class SentenceBuffer:
    def __init__(self, limit: int) -> None: ...
    @property
    def retained_bytes(self) -> int: ...
    @property
    def scans(self) -> int: ...
    def feed(self, text: str, final_input: bool) -> list[str]: ...

class Converter:
    def __init__(self, profile: str) -> None: ...
    def process(self, data: bytes, final_input: bool) -> bytes: ...
